/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlysinhvien;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.Reader;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import static quanlysinhvien.GiaoVu.th;


/**
 *
 * @author yumil
 */
public class QuanLyMonHoc extends javax.swing.JFrame {
    private final int IMPORT_FILE = 1;
    private final int IMPORT_FILE_SCORE = 2;
    themSinhVien sv;
    xoaSinhVien xoasv;
    private String[] columName = {
        "STT", "MSSV", "Họ Tên", "Giới Tính", "CMND"
    };
    private final String[] columnNameDiem = {
        "STT", "MSSV", "Họ tên", "Điểm GK", "Điểm CK", "Điểm khác", "Điểm tổng", "Kết quả"
    };
    /**
     * Creates new form QuanLyLopHoc
     */
    public QuanLyMonHoc() {
        initComponents();
         initLayout();
    }
private void initLayout() {        
        jsvTable.setVisible(false);
        panelUpdate.setVisible(false);
        panelThongKe.setVisible(false);
        if (th.getsoLop() > 0) {
            addDataForComboBoxClass();
        }
           addDataForTableMonHoc();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jbtnXoaSV = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbLop_MonHoc = new javax.swing.JComboBox();
        btnImport = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jsvTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jsvTableDiem = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jbtnThoat = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnQLTKB = new javax.swing.JButton();
        btnQLLH = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        panelThongKe = new javax.swing.JPanel();
        labelThongKe = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        textSLPass = new javax.swing.JTextField();
        textTLPass = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        textSLFail = new javax.swing.JTextField();
        textTLFail = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jbtnImportDiem = new javax.swing.JButton();
        jbtnXemBangDiem = new javax.swing.JButton();
        panelUpdate = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textGK = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        textMSSV = new javax.swing.JTextField();
        textKhac = new javax.swing.JTextField();
        textCK = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý môn học");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Thêm SV");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbtnXoaSV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnXoaSV.setText("Xóa SV");
        jbtnXoaSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnXoaSVActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Danh sách SV Môn");

        cbLop_MonHoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbLop_MonHoc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));
        cbLop_MonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLop_MonHocActionPerformed(evt);
            }
        });

        btnImport.setText("Import");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        jScrollPane1.setAutoscrolls(true);

        jsvTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jsvTable.setAutoscrolls(false);
        jsvTable.setColumnSelectionAllowed(true);
        jsvTable.setFocusable(false);
        jScrollPane1.setViewportView(jsvTable);
        jsvTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jScrollPane2.setAutoscrolls(true);

        jsvTableDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jsvTableDiem.setAutoscrolls(false);
        jsvTableDiem.setFocusable(false);
        jsvTableDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jsvTableDiemMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jsvTableDiem);
        jsvTableDiem.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Bảng điểm");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1198, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbLop_MonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnImport)
                        .addGap(41, 41, 41)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jbtnXoaSV)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbLop_MonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImport)
                    .addComponent(jButton1)
                    .addComponent(jbtnXoaSV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jbtnThoat.setText("Thoát");
        jbtnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThoatActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 51)));

        btnQLTKB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnQLTKB.setText("Quản Lý TKB");
        btnQLTKB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLTKBActionPerformed(evt);
            }
        });

        btnQLLH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnQLLH.setText("Quản Lý Lớp Học");
        btnQLLH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLLHActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Chức năng khác");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnQLTKB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLLH, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnQLLH, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnQLTKB, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelThongKe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));

        labelThongKe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelThongKe.setText("Thống Kê");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 255, 0));
        jLabel11.setText("Đậu");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Số Lượng:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Tỉ Lệ (%):");

        textSLPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textSLPass.setText("0");
        textSLPass.setEnabled(false);
        textSLPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSLPassActionPerformed(evt);
            }
        });

        textTLPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textTLPass.setText("0");
        textTLPass.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 51, 51));
        jLabel14.setText("Rớt");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Số Lượng:");

        textSLFail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textSLFail.setText("0");
        textSLFail.setEnabled(false);

        textTLFail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textTLFail.setText("0");
        textTLFail.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Tỉ Lệ (%):");

        javax.swing.GroupLayout panelThongKeLayout = new javax.swing.GroupLayout(panelThongKe);
        panelThongKe.setLayout(panelThongKeLayout);
        panelThongKeLayout.setHorizontalGroup(
            panelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongKeLayout.createSequentialGroup()
                .addGroup(panelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelThongKeLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel11))
                    .addGroup(panelThongKeLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(panelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textSLPass, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addComponent(textTLPass))))
                .addGap(54, 54, 54)
                .addGroup(panelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelThongKeLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(21, 21, 21)
                        .addComponent(textSLFail))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelThongKeLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textTLFail, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelThongKeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(70, 70, 70)))
                .addGap(64, 64, 64))
            .addGroup(panelThongKeLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(labelThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelThongKeLayout.setVerticalGroup(
            panelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongKeLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelThongKe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel11))
                .addGap(9, 9, 9)
                .addGroup(panelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSLPass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15)
                    .addComponent(textSLFail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(panelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTLPass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(textTLFail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Bảng Điểm");

        jbtnImportDiem.setText("Import");
        jbtnImportDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnImportDiemActionPerformed(evt);
            }
        });

        jbtnXemBangDiem.setText("Xem bảng điểm");
        jbtnXemBangDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnXemBangDiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jbtnXemBangDiem)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jbtnImportDiem)
                                .addGap(29, 29, 29))))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnImportDiem)
                .addGap(18, 18, 18)
                .addComponent(jbtnXemBangDiem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Cập Nhật Điểm");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("MSSV: ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Họ Tên:");

        textName.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Điểm CK:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Điểm GK:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel17.setText("Điểm Khác:");

        textMSSV.setEnabled(false);

        btnUpdate.setBackground(new java.awt.Color(0, 153, 153));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdate.setText("Lưu");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUpdateLayout = new javax.swing.GroupLayout(panelUpdate);
        panelUpdate.setLayout(panelUpdateLayout);
        panelUpdateLayout.setHorizontalGroup(
            panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpdateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpdateLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(190, 190, 190))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpdateLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textGK, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textCK, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpdateLayout.createSequentialGroup()
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151))))
        );
        panelUpdateLayout.setVerticalGroup(
            panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textGK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(textCK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(textKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 159, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý môn học");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(253, 253, 253)
                .addComponent(jbtnThoat)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jbtnThoat))
                .addGap(11, 11, 11)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        // TODO add your handling code here:
           importExportFile("Choose file import", IMPORT_FILE);
    }//GEN-LAST:event_btnImportActionPerformed

    private void cbLop_MonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLop_MonHocActionPerformed
        // TODO add your handling code here: 
        if(cbLop_MonHoc.getSelectedItem().toString().equals("--")){
            JOptionPane.showMessageDialog(null, "!!! Chưa Có Danh Sách Lớp");
        } else{
            addDataForTableMonHoc();
        }
        
    }//GEN-LAST:event_cbLop_MonHocActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      String lop_MH = String.valueOf(cbLop_MonHoc.getItemAt(cbLop_MonHoc.getSelectedIndex()));
      String [] item = lop_MH.split("-");
        if (cbLop_MonHoc.getSelectedIndex() < 0){
            JOptionPane.showMessageDialog(null, "!!! Vui Lòng Chọn Môn Học");
        } else {
                sv = new themSinhVien(item[0], item[1]);
                sv.setVisible(true);
        }  
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnXoaSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnXoaSVActionPerformed
        // TODO add your handling code here:
        String lop_MH = String.valueOf(cbLop_MonHoc.getItemAt(cbLop_MonHoc.getSelectedIndex()));
       // System.out.printf(lop_MH);
        if (cbLop_MonHoc.getSelectedIndex() < 0){
            JOptionPane.showMessageDialog(null, "!!! Vui Lòng Chọn Môn Học");
        } else {
                xoasv = new xoaSinhVien(lop_MH);
                xoasv.setVisible(true);
        }  
    }//GEN-LAST:event_jbtnXoaSVActionPerformed

    private void jbtnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new GiaoVu().setVisible(true);
    }//GEN-LAST:event_jbtnThoatActionPerformed

    private void jbtnImportDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnImportDiemActionPerformed
        // TODO add your handling code here:
        importExportFile("Choose file import", IMPORT_FILE_SCORE);
    }//GEN-LAST:event_jbtnImportDiemActionPerformed

    private void jbtnXemBangDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnXemBangDiemActionPerformed
        // TODO add your handling code here:
        jsvTableDiem.setRowSelectionAllowed(true);
        jsvTableDiem.setEnabled(true);
                
        DefaultTableModel table = new DefaultTableModel();
       
        String valueComboBox = cbLop_MonHoc.getSelectedItem().toString();  
         String[] a = valueComboBox.split("-");
         
         Lop_MonHoc lop_MH = th.getLopMH(valueComboBox);
        
         table.setColumnIdentifiers(columnNameDiem);
        
        ArrayList<Diem> listDiem = lop_MH.getListDiem();
        
        int stt = 1;
        if(listDiem.size() > 0){
            for(Diem item : listDiem){
                String[] rows = new String[8];
                rows[0] = String.valueOf(stt);
                rows[1] = item.getSV().getMSSV();
                rows[2] = item.getSV().getTen();
                rows[3] = String.valueOf(item.getDiemGK());
                rows[4] = String.valueOf(item.getDiemCK());
                rows[5] = String.valueOf(item.getDiemKhac());
                rows[6] = String.valueOf(item.getDiemTong());
                rows[7] = item.xepLoai();

                table.addRow(rows);
                stt++;
            }
            jsvTableDiem.setModel(table);
            jsvTableDiem.setVisible(true);
            panelUpdate.setVisible(true);
             panelThongKe.setVisible(true);      
             
            DecimalFormat decimalFormat = new DecimalFormat("#.##");
           
            textSLPass.setText(String.valueOf(lop_MH.tongDau()));
            textTLPass.setText(String.valueOf(Float.valueOf(decimalFormat.format(lop_MH.tiLeDau()))));
            textSLFail.setText(String.valueOf(lop_MH.tongRot()));
            textTLFail.setText(String.valueOf(Float.valueOf(decimalFormat.format(lop_MH.tiLeRot()))));
        } else {
            jsvTableDiem.setModel(table);
            panelUpdate.setVisible(false);
             panelThongKe.setVisible(false);      
            JOptionPane.showMessageDialog(null, "!!! Chưa Có Bảng Điểm");
        }
    }//GEN-LAST:event_jbtnXemBangDiemActionPerformed

    private void textSLPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSLPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSLPassActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String maMH = cbLop_MonHoc.getSelectedItem().toString();
        int i = jsvTableDiem.getSelectedRow();

        DefaultTableModel model = (DefaultTableModel) jsvTableDiem.getModel();
        DecimalFormat decimalFormat = new DecimalFormat("#.##");

        boolean checked = kiemTraDiem();

        if(i >= 0 && !checked){
            String mssv = (String) jsvTableDiem.getValueAt(i, 1);
            String xepLoai = (String) jsvTableDiem.getValueAt(i, 7);

            float diemGK = Float.parseFloat(textGK.getText());
            float diemCK = Float.parseFloat(textCK.getText());
            float diemKhac = Float.parseFloat(textKhac.getText());
            float diemTong = Float.valueOf(decimalFormat.format((diemGK + diemCK + diemKhac)/3));

            model.setValueAt(textGK.getText(), i, 3);
            model.setValueAt(textCK.getText(), i, 4);
            model.setValueAt(textKhac.getText(), i, 5);
            model.setValueAt(diemTong, i, 6);

            if(diemTong < 5){
                xepLoai = "Rớt";
            } else {
                xepLoai = "Đậu";
            }
            model.setValueAt(xepLoai, i, 7);


            updateDiem(maMH, mssv);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jsvTableDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsvTableDiemMouseClicked
        // TODO add your handling code here:
         int index = jsvTableDiem.getSelectedRow();
            TableModel md = jsvTableDiem.getModel();
            String mssv = md.getValueAt(index, 1).toString();
            String hoTen = md.getValueAt(index, 2).toString();
            String diemGK = md.getValueAt(index, 3).toString();
            String diemCK = md.getValueAt(index, 4).toString();
            String diemKhac = md.getValueAt(index, 5).toString();

            textMSSV.setText(mssv);
            textName.setText(hoTen);
            textGK.setText(diemGK);
            textCK.setText(diemCK);
            textKhac.setText(diemKhac);
    }//GEN-LAST:event_jsvTableDiemMouseClicked

    private void btnQLLHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLLHActionPerformed
        // TODO add your handling code here:
        new QuanLyLopHoc().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLLHActionPerformed

    private void btnQLTKBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLTKBActionPerformed
        // TODO add your handling code here:
         new QuanLyTKB().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLTKBActionPerformed
private void importExportFile(String title, int key) {
        JFileChooser j = new JFileChooser();
        j.setDialogTitle(title);
        int choose = -1;
        switch (key) {
            case IMPORT_FILE:
                choose = j.showOpenDialog(null);
                break;
             case IMPORT_FILE_SCORE:
               choose = j.showOpenDialog(null);
                break;
        }

        if (choose == JFileChooser.APPROVE_OPTION) {
            File f = j.getSelectedFile();
            switch (key) {
                case IMPORT_FILE:
                    readFile(f);
                    break;
                 case IMPORT_FILE_SCORE:
                    readFileScore(f);
                    break;
            }
        }
    }
private boolean kiemTraDiem() {
        boolean valid = false;
        double diemGK = 0;
        double diemCK = 0;
        double diemKhac = 0;

        if (textGK.getText().equals("") || textCK.getText().equals("") || textKhac.getText().equals("")) {
            valid = true;
            JOptionPane.showMessageDialog(null, "Thông tin không đủ", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            diemGK = Float.parseFloat(textGK.getText());
            diemCK = Float.parseFloat(textCK.getText());
            diemKhac = Float.parseFloat(textKhac.getText());
            
            if ((diemGK > 10 || diemGK < 0) || (diemCK > 10 || diemCK < 0) || (diemKhac > 10 || diemKhac < 0)) {
                valid = true;
                JOptionPane.showMessageDialog(null, "Điểm không hợp lệ!!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                valid = false;
            }
        }
        return valid;
    }
 private void addDataForComboBoxClass(){
        ArrayList<Lop_MonHoc> listLH = th.getListLopMH();
        DefaultComboBoxModel cbModel = new DefaultComboBoxModel();
            
        for (Lop_MonHoc i : listLH) {
            String name = i.getTenLopMH();
            cbModel.addElement(name);   
        }          
        cbLop_MonHoc.setModel(cbModel);
    }
  private void addDataForTableMonHoc(){
        
        String select = getClassNameInComboBox();
        ArrayList<Lop_MonHoc> listLH = th.getListLopMH(); 
        DefaultTableModel tbModel = new DefaultTableModel();
        
        int stt = 1;
        
        for (Lop_MonHoc i : listLH) {
            if(select.equalsIgnoreCase(i.getTenLopMH())){
                jsvTable.setVisible(true);
                tbModel.setColumnIdentifiers(columName);
                                                
                ArrayList<SinhVien> listSV = new ArrayList<SinhVien>();
                listSV = i.getListSV();
                for (SinhVien sv : listSV) {
                    
                    String[] info = new String[5];
                    info[0] = String.valueOf(stt);
                    info[1] = sv.getMSSV();
                    info[2] = sv.getTen();
                    if (sv.getGioiTinh() == 0) {
                        info[3] = "Nữ";
                    } else {
                        info[3] = "Nam";
                    }
                    info[4] = sv.getCMND();

                    tbModel.addRow(info);
                    stt++;
                }
                jsvTable.setModel(tbModel);
            } 
            else{
                tbModel.setColumnIdentifiers(columName);
                jsvTable.setModel(tbModel);
            }            
        }
    }
  
  private void readFile(File file) {
        try {
           try( FileInputStream fileInPutStream = new FileInputStream(file)){
            Reader reader = new java.io.InputStreamReader(fileInPutStream, "utf8");
            BufferedReader buffer = new BufferedReader(reader);

                String line;
                line = buffer.readLine();
                 
                String[] tenLop = line.split(",");
              //  System.out.printf(tenLop[0]);
                
                Lop_MonHoc lh = th.getLopMH(tenLop[0]);
              //   System.out.printf(lh.getTenLopMH());
                 boolean checkLopHoc = true;
                    if (lh.getTenLopMH().equals("")) {
                        checkLopHoc = false;
                        lh.setTenLopMH(tenLop[0]);
                    }
                if (checkLopHoc == true) {
                    lh.getListSV().clear();
                    th.setLopMH(tenLop[0], lh);
                    JOptionPane.showMessageDialog(null, "!!! Class Already Exists");                    
                } else {
                    th.themLopMH(lh);
                    while ((line = buffer.readLine()) != null) {
                        String[] info = line.split(",");
                        
                        SinhVien sv = new SinhVien();
                        sv.setMSSV(info[1]);
                        sv.setTen(info[2]);
                        sv.setCMND(info[4]);
                        int gt = -1;

                        if (info[3].equalsIgnoreCase("Nam")) {
                            gt = 1;
                        }
                        if (info[3].equalsIgnoreCase("Nữ")) {
                            gt = 0;
                        }

                        sv.setGioiTinh(gt);
                        lh.themSV(sv);
                    }
                }
                buffer.close();
            }
                   initLayout();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error to open file: " + e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
           
        }

  }
  private void updateDiem(String lop, String mssv){
        boolean checked = kiemTraDiem();
        if (!checked) {
            
            Lop_MonHoc l_mh = th.getLopMH(lop);
            Diem diem = l_mh.getDiemSV(mssv);
            DecimalFormat decimalFormat = new DecimalFormat("#.##");
            
            float diemGK = Float.parseFloat(textGK.getText());
            float diemCK = Float.parseFloat(textCK.getText());
            float diemKhac = Float.parseFloat(textKhac.getText());
            float diemTong = (diemGK + diemCK + diemKhac)/3;
            
            diem.setDiemGK(Float.valueOf(decimalFormat.format(diemGK)));
            diem.setDiemCK(Float.valueOf(decimalFormat.format(diemCK)));
            diem.setDiemKhac(Float.valueOf(decimalFormat.format(diemKhac)));
            diem.setDiemTong(Float.valueOf(decimalFormat.format(diemTong)));

            l_mh.setDiem(diem, mssv);            
            th.setLopMH(lop, l_mh);
            
            JOptionPane.showMessageDialog(null, "!!! Cập Nhật Thành Công");
            
            textMSSV.setText("");
            textName.setText("");
            textGK.setText("");
            textCK.setText("");
            textKhac.setText("");
            
            float tileDau = Float.valueOf(decimalFormat.format(l_mh.tiLeDau()));
            float tileRot = Float.valueOf(decimalFormat.format(l_mh.tiLeRot()));
            textSLPass.setText(String.valueOf(decimalFormat.format(l_mh.tongDau())));
            textTLPass.setText(String.valueOf(tileDau));
            textSLFail.setText(String.valueOf(l_mh.tongRot()));
            textTLFail.setText(String.valueOf(tileRot));
        }
    }
     private void readFileScore(File file) {
        try {
           try( FileInputStream fileInPutStream = new FileInputStream(file)){
            Reader reader = new java.io.InputStreamReader(fileInPutStream, "utf8");
            BufferedReader buffer = new BufferedReader(reader);

            String line;
            line = buffer.readLine();
            String [] valueComboBox = line.split(",");
            Lop_MonHoc lop_MonHoc = th.getLopMH(valueComboBox[0]);
            
            ArrayList<Diem> listDiem = lop_MonHoc.getListDiem();
            listDiem.clear();
            
            while((line = buffer.readLine()) != null){
                String[] diem = line.split(",");
                 
                Diem diemSV = new Diem();
                SinhVien s = new SinhVien(diem[0], diem[1]);
                diemSV.setSV(s);                
                diemSV.setDiemGK(Float.parseFloat(diem[2]));
                diemSV.setDiemCK(Float.parseFloat(diem[3]));
                diemSV.setDiemKhac(Float.parseFloat(diem[4]));
                diemSV.setDiemTong(Float.parseFloat(diem[5]));
                listDiem.add(diemSV);
            }
            lop_MonHoc.setListDiemSV(listDiem);
            th.setLopMH(valueComboBox[0], lop_MonHoc);
            buffer.close();
            initLayout();
        }
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error to export file: " + e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }        
    }
    
    private String getClassNameInComboBox(){
        String result = cbLop_MonHoc.getSelectedItem().toString();
        return result;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyMonHoc().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnQLLH;
    private javax.swing.JButton btnQLTKB;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cbLop_MonHoc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnImportDiem;
    private javax.swing.JButton jbtnThoat;
    private javax.swing.JButton jbtnXemBangDiem;
    private javax.swing.JButton jbtnXoaSV;
    private javax.swing.JTable jsvTable;
    private javax.swing.JTable jsvTableDiem;
    private javax.swing.JLabel labelThongKe;
    private javax.swing.JPanel panelThongKe;
    private javax.swing.JPanel panelUpdate;
    private javax.swing.JTextField textCK;
    private javax.swing.JTextField textGK;
    private javax.swing.JTextField textKhac;
    private javax.swing.JTextField textMSSV;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textSLFail;
    private javax.swing.JTextField textSLPass;
    private javax.swing.JTextField textTLFail;
    private javax.swing.JTextField textTLPass;
    // End of variables declaration//GEN-END:variables
}
